# Generated by Django 5.2.4 on 2025-08-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_id', models.CharField(max_length=255, null=True, unique=True)),
                ('fullname', models.CharField(default='', max_length=255)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('blocked', 'Blocked'), ('activated', 'Activated'), ('unverified', 'Unverified')], max_length=20)),
                ('role', models.CharField(choices=[('root', 'Root'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
